import localFont from 'next/font/local'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { Roboto } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'
import theme from '../theme'
import ShoppingCartIcon from '@mui/icons-material/ShoppingCart'
const roboto = Roboto({
   weight: ['300', '400', '500', '700'],
   subsets: ['latin'],
   display: 'swap',
   variable: '--font-roboto',
})

const geistSans = localFont({
   src: './fonts/GeistVF.woff',
   variable: '--font-geist-sans',
   weight: '100 900',
})
const geistMono = localFont({
   src: './fonts/GeistMonoVF.woff',
   variable: '--font-geist-mono',
   weight: '100 900',
})

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export const NAVIGATION = [
   // ...
   {
      segment: 'orders',
      title: 'Orders',
      icon: <ShoppingCartIcon />,
   },
   // ...
]

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body
            //   className={`${geistSans.variable} ${geistMono.variable}`}
            className={roboto.variable}
         >
            <AppRouterCacheProvider>
               <ThemeProvider theme={theme}>
            {children} 
               </ThemeProvider>
            </AppRouterCacheProvider>
         </body>
      </html>
   )
}
//https://mui.com/material-ui/integrations/nextjs/
